### PR TITLE
Enhanced UX

### PR DESCRIPTION
**Pull request by RealEzra**
Cool project I thought I'd suggest some changes
I also forgot to mention that the background of the slider is colored based on slider position so when the slider is turned all the way down it cannot be seen except for the slider thumb you can see it in the attached screenshot.
NewLook

### CODE REVIEW

**Comment by RealEzra** [comment]
Slider coloring based on the 3d image on the stem player website

**Comment by lukew3** [comment]
Hey, @RealEzra. Glad you like the project. I appreciate the input. I've already moved away from the slider implementation, so I won't be implementing those changes. I like the colors though. I'll probably implement your color scheme and figure out how to make the dots colored and pulsing tomorrow.

**Comment by RealEzra** [comment]
Glad to help. Do you have a discord I may have some useful ideas and I figured out away to use the official stem player api to make request, so we could implement it into this project and people can upload a song to be processed through the api and generate the 4 stems. Of course they could make their api more secure in the future which would kill this whole idea.

**Comment by lukew3** [comment]
@RealEzra I like it. My discord is lukew3#6464

**Pull request closed without merging**
